### ISSUE TITLE
iOS 10 requires Swift 3.0 code.

### ISSUE THREAD

**Issue by rakeshpalivela** [cowbell/cordova-plugin-geofence#174] opened 2016-09-15 04:03 UTC
When I am running this code in Xcode 8.2 beta, It is throwing lot of errors. Most of them were deprecated. Can you please help to solve this.

**Comment by sumedh908** [comment] 2016-09-15 11:30
I am facing the same issue. I have recently updated Xcode to 8.0 for latest iOS 10 SDK. When I build the project, I am getting a bunch of errors (deprecated and warnings).
Can you please implement as soon as possible the above fix in the new version of plugin. Can you also please inform about possible date in which new plugin would be available?

**Comment by matheusbodorede** [comment] 2016-09-15 11:49
Hi,
I'm in the same way, after I've updated my Xcode, my app with this plugin doesn't compile anymore.

Is It expected a Swift 3 version?

Thanks.

**Comment by Marjoel** [comment] 2016-09-15 11:50
Hi,
I'm in the same way, after I've updated my Xcode, my app with this plugin doesn't compile anymore.

Is It expected a Swift 3 version?

Thanks.

**Comment by ezazwar1** [comment] 2016-09-22 18:55
+1

**Comment by inceptiveDipak** [comment] 2016-09-23 07:47
+1

**Comment by yamada28go** [comment] 2016-09-23 08:28
+1

**Comment by mizutuu** [comment] 2016-09-23 08:28
+1

**Comment by ezazwar1** [comment] 2016-09-23 10:44
can you please fix this issue @tsubik

**Comment by echotech11** [comment] 2016-09-23 12:46
+1

**Comment by ElieSauveterre** [comment] 2016-09-24 23:23
+1

**Comment by cutout33** [comment] 2016-09-25 09:24
+1 this is really urgent my apps stopped working and I have to upgrade to iOS 10!

**Comment by AlexisReverte** [comment] 2016-09-26 13:25
For now, I use the compiler parameter option "Use Legacy Swift Language Version" to "Yes", and it's building.

**Comment by ezazwar1** [comment] 2016-09-26 14:25
which Xcode are you using @AlexisReverte

**Comment by ezazwar1** [comment] 2016-09-26 14:26
Can you Please describe in detail what compiler parameter are you specifying @AlexisReverte

**Comment by raphagodoi** [comment] 2016-09-27 02:33
If I use the @AlexisReverte workaround, it building.. but I'm using fastlane to automate deploys.. and I can't use fastlane until this fix...

+1

**Comment by EddyVerbruggen** [comment] 2016-09-27 06:45
Should be fixed with #178

**Comment by Wade-BuildOtto** [comment] 2016-10-14 16:26
All the other plugin's to make my app work require Swift 3

**Comment by cdecaux** [comment] 2016-12-13 10:14
+1
Swift 2.3 is not enough anymore
Swift 3 is required for those who use other plugins (which are already in Swift 3)
Thanks a lot in advance

**Comment by RomanovX** [comment] 2017-01-13 14:41
+1

**Comment by rupalpatel0008** [comment] 2017-02-01 11:50
+1

**Comment by jokiamo** [comment] 2017-04-12 12:22
+1

**Comment by tsubik** [comment] 2017-05-14 19:32
Duplicate of https://github.com/cowbell/cordova-plugin-geofence/issues/215

**Closed by tsubik** 2017-05-14 19:32 UTC
