### ISSUE TITLE
can we increase the Limit

### ISSUE THREAD

**Issue by ezazwar1** [cowbell/cordova-plugin-geofence#181] opened 2016-10-01 09:52 UTC
hey i am currently trying to implement geofence and i am only able to register 20 notifications in ios can we increase the number??

**Comment by Wade-BuildOtto** [comment] 2016-10-11 16:39
that is a device limit.

**Comment by tsubik** [comment] 2016-10-23 14:55
Duplicate of #15

**Closed by tsubik** 2016-10-23 14:55 UTC
