### ISSUE TITLE
Transitions in Android can't be handled in the background?

### ISSUE THREAD

**Issue by shtaif** [cowbell/cordova-plugin-geofence#86] opened 2015-09-28 10:09 UTC
I'm not really familiar with Android programming.

From my first attempt after implementing this plugin in Android, the geofence.onTransitionReceived seems to have been called only the moment I launched the app myself, and not silently in the background the moment I crossed the geofences, as I have come to understand that it should.

From my tests with the iOS version of my app, it seemed to have worked in the background fine. But I saw the section about implementing that BroadcastReceiver thing and I've come to wonder - does the Android code in this plugin must rely on some personal implementation in native code for it to respond in the background, or can it do this straight out of the box?

**Comment by tsubik** [comment] 2015-09-30 15:02
You are right, on Android it doesn't trigger onTransitionReceived javascript handler in background. You can handle some cases using native java code [described here](https://github.com/cowbell/cordova-plugin-geofence#listening-for-geofence-transitions-in-native-code) or maybe try with [background mode plugin](https://github.com/katzer/cordova-plugin-background-mode) (I haven't tried it, though).

**Comment by ramon-bistuer** [comment] 2015-10-27 09:01
Hi! Is this feature a future implementation? This plugin would be very valuable working on backroung in Android.

**Comment by johnrobertcobbold** [comment] 2015-10-27 09:01
+1

**Comment by jrbistuer** [comment] 2015-10-27 09:02
Hi! Is this feature a future implementation? This plugin would be very valuable working on backroung in Android.

**Comment by tsubik** [comment] 2016-01-22 10:43
Duplicate of #53

**Closed by tsubik** 2016-01-22 10:43 UTC
