### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by marcovisona** [cowbell/cordova-plugin-geofence#172] opened 2016-09-12 14:44 UTC
Hello,
   it is expected a swift 3 version of this plugin? At the moment it doesn't compile in Xcode 8

Thank you very much

**Comment by Marjoel** [comment] 2016-09-14 21:36
Hi,
I'm in the same way, after I've updated my Xcode, my app with this plugin doesn't compile anymore.

Is It expected a Swift 3 version?

Thanks.

**Comment by ezazwar1** [comment] 2016-09-22 19:41
+1

**Comment by ElieSauveterre** [comment] 2016-09-24 23:23
+1

**Comment by Wade-BuildOtto** [comment] 2016-10-11 20:08
+1

**Comment by friedolinfoerder** [comment] 2016-10-26 13:53
+1

**Comment by tsubik** [comment] 2017-05-14 19:32
Duplicate of https://github.com/cowbell/cordova-plugin-geofence/issues/215

**Closed by tsubik** 2017-05-14 19:32 UTC
