### ISSUE TITLE
Error on Build

### ISSUE THREAD

**Issue by ormit** [cowbell/cordova-plugin-geofence#190] opened 2016-11-23 11:35 UTC
Getting the following error on build : 

/cordova-plugin-geofence/GeofencePlugin.swift:35:23: error: expected expression in list of expressions
           selector: #selector(GeofencePlugin.didReceiveLocalNotification(_:))

Any ideas ?

**Comment by tsubik** [comment] 2017-05-14 19:31
Probably duplicate of https://github.com/cowbell/cordova-plugin-geofence/issues/215

**Closed by tsubik** 2017-05-14 19:31 UTC
