### ISSUE TITLE
Crashes on consecutive geofence transitions on Android

### ISSUE THREAD

**Issue by PaperMonster** [cowbell/cordova-plugin-geofence#73] opened 2015-08-13 05:15 UTC
After entering and exiting geofences for several times consecutively (around 10+ times), my app crashes with the following error:
````
08-13 11:36:21.507: E/AndroidRuntime(6849): FATAL EXCEPTION: IntentService[ReceiveTransitionsIntentService]
08-13 11:36:21.507: E/AndroidRuntime(6849): Process: com.myapp.geofenceapp, PID: 6849
08-13 11:36:21.507: E/AndroidRuntime(6849): java.lang.RuntimeException: Init failed
08-13 11:36:21.507: E/AndroidRuntime(6849): 	at android.media.ToneGenerator.native_setup(Native Method)
08-13 11:36:21.507: E/AndroidRuntime(6849): 	at android.media.ToneGenerator.<init>(ToneGenerator.java:746)
08-13 11:36:21.507: E/AndroidRuntime(6849): 	at com.cowbell.cordova.geofence.BeepHelper.<init>(BeepHelper.java:10)
08-13 11:36:21.507: E/AndroidRuntime(6849): 	at com.cowbell.cordova.geofence.GeoNotificationNotifier.<init>(GeoNotificationNotifier.java:23)
08-13 11:36:21.507: E/AndroidRuntime(6849): 	at com.cowbell.cordova.geofence.ReceiveTransitionsIntentService.onHandleIntent(ReceiveTransitionsIntentService.java:56)
08-13 11:36:21.507: E/AndroidRuntime(6849): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
08-13 11:36:21.507: E/AndroidRuntime(6849): 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-13 11:36:21.507: E/AndroidRuntime(6849): 	at android.os.Looper.loop(Looper.java:135)
08-13 11:36:21.507: E/AndroidRuntime(6849): 	at android.os.HandlerThread.run(HandlerThread.java:61)
````

I tested this with Nexus 5 running Lockito app (location simulation app) which simulated driving along a street with 8 geofences on the side. I set transition type to both enter and exit. The first trip went smooth, but when I run the simulation again the app crashed in the background.

The issue is likely to be related to [ToneGenerator being used repeatedly in the app without releasing media player resources](https://code.google.com/p/android/issues/detail?id=91773).

**Comment by tsubik** [comment] 2015-09-02 17:13
@PaperMonster I cannot reproduce that, have you found out any solution for this?

**Comment by PaperMonster** [comment] 2015-09-03 03:43
I just removed the line `beepHelper.startTone("beep_beep_beep");` to avoid the crash. But I've just discovered I got the old plugin version. The current version use RingtoneManager instead of Beeper (as changed in [this commit](https://github.com/cowbell/cordova-plugin-geofence/commit/9270c5d25cee7f02b9692d463c849852df3196bd)) and now Beeper is only used as a fallback. Let me try updating the plugin version and test everything out again.

**Comment by Tempus35** [comment] 2016-01-18 21:20
I have this issue as well, using plugin 0.5.0.

````
01-18 14:15:38.899: E/AndroidRuntime(16894): FATAL EXCEPTION: IntentService[ReceiveTransitionsIntentService]
01-18 14:15:38.899: E/AndroidRuntime(16894): Process: com.vilocity.gilarivercasinos, PID: 16894
01-18 14:15:38.899: E/AndroidRuntime(16894): java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
01-18 14:15:38.899: E/AndroidRuntime(16894): 	at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:962)
01-18 14:15:38.899: E/AndroidRuntime(16894): 	at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:599)
01-18 14:15:38.899: E/AndroidRuntime(16894): 	at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
01-18 14:15:38.899: E/AndroidRuntime(16894): 	at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
01-18 14:15:38.899: E/AndroidRuntime(16894): 	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:834)
01-18 14:15:38.899: E/AndroidRuntime(16894): 	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
01-18 14:15:38.899: E/AndroidRuntime(16894): 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
01-18 14:15:38.899: E/AndroidRuntime(16894): 	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
01-18 14:15:38.899: E/AndroidRuntime(16894): 	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
01-18 14:15:38.899: E/AndroidRuntime(16894): 	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:258)
01-18 14:15:38.899: E/AndroidRuntime(16894): 	at com.cowbell.cordova.geofence.LocalStorage.getItem(LocalStorage.java:57)
01-18 14:15:38.899: E/AndroidRuntime(16894): 	at com.cowbell.cordova.geofence.GeoNotificationStore.getGeoNotification(GeoNotificationStore.java:20)
01-18 14:15:38.899: E/AndroidRuntime(16894): 	at com.cowbell.cordova.geofence.ReceiveTransitionsIntentService.onHandleIntent(ReceiveTransitionsIntentService.java:69)
01-18 14:15:38.899: E/AndroidRuntime(16894): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
01-18 14:15:38.899: E/AndroidRuntime(16894): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-18 14:15:38.899: E/AndroidRuntime(16894): 	at android.os.Looper.loop(Looper.java:148)
01-18 14:15:38.899: E/AndroidRuntime(16894): 	at android.os.HandlerThread.run(HandlerThread.java:61)
````

**Comment by tsubik** [comment] 2016-01-22 10:40
I guess it's fixed now.

**Closed by tsubik** 2016-01-22 10:40 UTC
